USE Ecommerce

-- =========================================================
-- MODERATE SQL QUESTIONS
-- =========================================================


-- Q3. Display each customer's name and the total number
-- of orders they have placed.
-- Include customers who have not placed any orders.

SELECT
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_orders DESC;


-- Q4. Find the total revenue generated by each product
-- from completed orders.
-- Display product name, category name, total units sold,
-- and total revenue.

SELECT
    p.product_name,
    c.category_name,
    SUM(oi.quantity) AS total_units_sold,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products p
JOIN categories c
    ON p.category_id = c.category_id
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY
    p.product_id,
    p.product_name,
    c.category_name
ORDER BY total_revenue DESC;


-- Q5. Find customers whose total spending is greater
-- than ₹50,000.
-- Display customer name, total orders, and total spending.
-- Consider only completed orders.

SELECT
    c.customer_name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.quantity * oi.unit_price) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY
    c.customer_id,
    c.customer_name
HAVING total_spending > 50000
ORDER BY total_spending DESC;


-- Q6. Find the number of successful and failed payments
-- for each payment method.
-- Display payment method, successful payments,
-- failed payments, and total payments.

SELECT
    payment_method,
    SUM(
        CASE
            WHEN payment_status = 'Successful' THEN 1
            ELSE 0
        END
    ) AS successful_payments,
    SUM(
        CASE
            WHEN payment_status = 'Failed' THEN 1
            ELSE 0
        END
    ) AS failed_payments,
    COUNT(*) AS total_payments
FROM payments
GROUP BY payment_method
ORDER BY total_payments DESC;